### ISSUE TITLE
Default list?

### ISSUE THREAD

**Issue by edsu** [jbolda/gatsby-source-airtable#126]
I have an Airtable column that can link to multiple records. I'm able to retrieve these fine in GraphQL but when the column is empty I get a *null* instead of an empty list *[ ]*. Is there any way to ensure that I get an empty list instead?

**Comment by jbolda** [comment]
👋 I believe this is a combination of default behavior from airtable combined with gatsby. Airtable will not include a field if it is empty. When gatsby goes through the step to infer the schema of the data, it will just make fields `null` if there is no defined value. I think I would likely recommend the [`createSchemaCustomization`](https://www.gatsbyjs.org/docs/node-apis/#createSchemaCustomization) lifecycle in gatsby where you can define the schema rather than having gatsby guess for you.
