### ISSUE TITLE
"error while running the sourceNodes lifecycle"

### ISSUE THREAD

**Issue by k-tests** [jbolda/gatsby-source-airtable#274]
Thanks in advance for any ideas of how to go about this Error? 
 ____
 ERROR #11321  PLUGIN

**"gatsby-source-airtable" threw an error while running the sourceNodes lifecycle:

warn The gatsby-source-airtable plugin has generated no Gatsby nodes. Do you need it?**
_____

my gatsby-config.js: 

      resolve: `gatsby-source-airtable`,
      options: {
        apiKey: `process.env.GATSBY_AIRTABLE_API_KEY`,
        tables: [
          {
            baseId: `appbLg1hdbwNbDqfV`,
            tableName: `Signals`,
            tableView: `Grid view`

**Comment by jbolda** [comment]
👋 

I am kind of surprised that you didn't get anymore of an error message...

Just to confirm based on what you shared, the `apiKey` that you are specifying, the `process.env` should _not_ be a string:
```js
  apiKey: process.env.GATSBY_AIRTABLE_API_KEY,
```

**Comment by Mangamaui** [comment]
I am running into the same issue.
At first my airtable setup worked but today I started getting the same error as @k-tests posted.

<img width="564" alt="Screenshot 2021-01-22 at 23 24 58" src="https://user-images.githubusercontent.com/3408929/105555206-2e6e4700-5d09-11eb-92c8-8ac8b99246a5.png">

**Comment by k-tests** [comment]
hey @thefrontside. Sorry for the delay and thanks for this. 
Both my ".env.development' and '.env.production' looks the same:
GATSBY_AIRTABLE_API_KEY=################ (the random API key sequence)
Hope that helps shed more light on this.

**Comment by billymitchell** [comment]
I'm getting the same error. 
`"gatsby-source-airtable" threw an error while running the sourceNodes lifecycle:`

I can confirm my key is not a string. 

https://github.com/billymitchell/billy-mitchell-design

**Comment by billymitchell** [comment]
I ran npm update --legacy-peer-deps and now it's working!

**Comment by iljapanic** [comment]
I'm getting the same error:

```bash
"gatsby-source-airtable" threw an error while running the sourceNodes lifecycle:
```

with no additional details.

I confirm that my `apiKey` is not a string. I've also tried updating legacy peer dependencies as @billymitchell suggested but to no avail.

The same code has been working fine before. I haven't changed anything related to the `gatsby-source-airtable`.

Is it possible that the error has to do something with the recent major Gatsby update to v3?

**Comment by iljapanic** [comment]
Ok, I've been banging my head for many hours but I've finally fixed it.

After trying various node environment variations* I was starting to get desperate. So I've started reducing the Airtable requests inside `gatsby-config.js` to a bare minimum and incrementally added more settings. I've realized the error is caused by the `tableLinks` property. It took me a while before I've realized that I have recently changed the name of one of the tables inside Airtable which was causing the empty error! 

So please **make sure table names in your Airtable and `gatsby-config.js` match**.

It would be great if the error message suggested this might be the issue.


Whilst upgrading my Node environments, I've noticed the following deprecation warning. I believe it was also caused by the linked tables:

```
(node:86336) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```

Well, that's it. I'm excited I got it fixed. Not even mad I've spent hours debugging a typo 😅




*I've tried all major versions of Node v10 through v15, I've tried downgrading to Gatsby v2 and React v16 because I was having some peer dependency issues. And I've tried various combinations of these. Still getting the same error.
