### ISSUE TITLE
Columns with no values are not mapped to node level data

### ISSUE THREAD

**Issue by jamessimone** [jbolda/gatsby-source-airtable#47]
For allAirtable / airtable queries, if your base's table has a column heading for, say, column3, but none of the rows have values for column3, making a graphql query using column3 returns an error with message:

` "message": "Cannot query field \"[column3]\" on type \"AirtableData\".",`

In my instance, column3 stands for a text field that will supply alt text, when appropriate - none of my records currently have alt text, and I want to have my application react dynamically depending on whether or not the alt text is there.

My workaround for now is to use a record with a value that I then filter in the allAirtable query - by having a record in the table with values in my column3 field but then filtering it, the other column3's for the records not excluded come across, as I would expect, as null.

Let me know if you need any more info, happy to assist!

**Comment by jbolda** [comment]
As far as I know, Airtable will not deliver fields with empty information. If you have a column with all of the rows blank, we will have no way of knowing that column even exists. Luckily we have two solid solutions to this. The easiest way would be to provide a default value (which appears to be undocumented in the readme, woops, but see [this release](https://github.com/jbolda/gatsby-source-airtable/releases/tag/2.0.5).) Otherwise, you can use the new schema definition API in Gatsby core.

**Comment by jamessimone** [comment]
@jbolda thanks for your response - let me check out the default values, I will close this if that works!

**Comment by jamessimone** [comment]
That worked, thanks!

**Comment by jbolda** [comment]
You're welcome. Happy to take a PR updating the docs if you have a free minute!

**Comment by jamessimone** [comment]
Sure thing!
