### ISSUE TITLE
Row order not being respected in a view

### ISSUE THREAD

**Issue by brandonweiss** [jbolda/gatsby-source-airtable#54]
Hey! I noticed that when specifying the `tableView` option that the results of the query do not come back in the same order as the records in the view.

For example, here are the records:

<img width="243" alt="Screen Shot 2019-06-09 at 12 51 16 PM" src="https://user-images.githubusercontent.com/4727/59163397-79483600-8ab5-11e9-9d16-f5461296bc25.png">

And here is the query and response:

<img width="726" alt="Screen Shot 2019-06-09 at 12 53 13 PM" src="https://user-images.githubusercontent.com/4727/59163401-92e97d80-8ab5-11e9-8b46-81cb7e3e1d85.png">

Thanks!

**Comment by jbolda** [comment]
Hmm, our documentation does seem to imply that the order should match. I believe at one point it did, but I wonder if with the more recent work in core that that has gone away. You may just need to use/add a column to run a gql sort on.

**Comment by jamessimone** [comment]
@jbolda I looked at the core code when this issue was first created but the view still gets passed through to Airtable so if the sorting was working and then it stopped, it must be a breaking change in their API. Of course, there might be the option to also specify sort order when passing the view to their API, but it doesn’t seem that anything changed on the plugin side.

**Comment by jbolda** [comment]
Oh, sorry I wasn't clear, I meant in gatsbyjs core. I don't know there is any guarantee that it will return the nodes in a specific order unless you supply a `sort` function in your query. I am thinking that it might have previously returned the nodes in the order they were created, but now they don't.

My other thought is we have dived deeper into promises. Maybe gatsbyjs _is_ returning the nodes in the order they were created, but our node creation (at least in this case) happens out of order due to promises lower on that list resolving sooner than higher on the list thereby mucking up the order.

**Comment by jbolda** [comment]
This seems to still be a consideration as seen in #95.
